image:
  digest: ''
  registry: ghcr.io
  repository: zcube/bitnami-compat/rabbitmq
  tag: 3.9.29-debian-11-r62
volumePermissions:
  image:
    digest: ''
    registry: ghcr.io
    repository: zcube/bitnami-compat/bitnami-shell
    tag: 11.0.0-debian-11-r62
